package ssp.smartstudentportal.Structures;

public enum Response {
    SUCCESS,
    FAILURE,
    ERROR,
    UPDATE_MESSAGES,
    UPDATE_USER_LIST,
    UPDATE_OTHER_USER_INFO, UPDATE_USER_INFO, UPDATE_POSTS, UPDATE_POST, UPDATE_TASK, TASK_ID, UPDATE_INDIVIDUAL_USER_INFO, GET_POSTS_FORUM, UPDATE_COMMENTS, UPDATE_FORUMS, UPDATE_TODO_LIST, GET_REMINDERS, UPDATE_COURSES, UPDATE_COMPLETED_COURSES, UPDATE_POST_FILES, UPDATE_SEARCH_USERNAMES
}
